apiVersion: v1
kind: ConfigMap
metadata:
  name: blockme-config
  namespace: blockme
data:
  LOG_FORMAT: "json"
  LOG_LEVEL: "INFO"
  LOG_LOCATION: "console"
  DB_TYPE: "sqlite"
  RESET_ME: "false"
  IGNORE_LIST: "127.0.0.1"
