apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockme-deployment
  namespace: blockme
spec:
  selector:
    matchLabels:
      app: blockme
  template:
    metadata:
      labels:
        app: blockme
    spec:
      containers:
        - name: blockme
          image: ghcr.io/t3ch404/blockme/blockme:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: blockme-config
