apiVersion: v1
kind: Service
metadata:
  name: blockme-service
  namespace: blockme
spec:
  type: ClusterIP
  selector:
    app: blockme
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  #  type: NodePort
  #  ports:
  #    - nodePort: 8080
  #      port: 8080
  #      protocol: TCP
  #      targetPort: 8080
